# Generated by Django 5.1.1 on 2024-10-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_banner_alter_category_name_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='promotional_products/')),
                ('description', models.TextField()),
            ],
        ),
    ]
